CREATE PROCEDURE PR_TB_USUARIO_TAREFA_INSERT
(
	@EMAIL_USUARIO VARCHAR(100),
	@ID_TAREFA INT
)
AS
BEGIN
	INSERT INTO USUARIO_TAREFA (EMAIL_USUARIO, ID_TAREFA)
	VALUES (@EMAIL_USUARIO, @ID_TAREFA);
END
