CREATE PROCEDURE [dbo].[PR_TB_USUARIO_INSERT]
(
	@NOME VARCHAR(100),
	@EMAIL VARCHAR(100),
	@SENHA VARCHAR(100)
	
)
AS
BEGIN
	INSERT INTO USUARIO (NOME, EMAIL, SENHA) VALUES (@NOME, @EMAIL, @SENHA);
END
