CREATE PROCEDURE [dbo].[PR_TB_LISTA_TAREFA_SELECT]
(
	@EMAIL VARCHAR(100)
	
)
AS
BEGIN
	SELECT ID, DATA, DESCRICAO, NOTIFICACAO, IDCATEGORIA,EMAIL_USUARIO
	FROM TAREFA WHERE EMAIL_USUARIO = @EMAIL;
END
GO
