CREATE PROCEDURE [dbo].[PR_TB_TAREFA_DELETE]
(
	@ID INT,
	@EMAIL VARCHAR(100)
	
)
AS
BEGIN
	DELETE FROM CONVIDADO_TAREFA WHERE ID_TAREFA = @ID;
	DELETE FROM TAREFA WHERE ID = @ID AND EMAIL_USUARIO = @EMAIL;
END
